### PR TITLE
Fix #570 Publishing script was using old jenkinsci repo

### LINKED ISSUE #570: apt-get appears missing from the latest (and lts) tags
I have a jenkins build that uses apt-get to include some packages I need for my environment. This was working this morning but I'm having issues with it now. Whenever I try to run apt-get in my Dockerfile I get:

```
bash-4.3$ apt-get
bash: apt-get: command not found
```

### Docker commands that you execute

```
sh-4.3# docker run -it --rm jenkins/jenkins:latest apt-get
```

### Actual result

```
/usr/local/bin/jenkins.sh: line 26: exec: apt-get: not found
```

### Expected outcome

Apt-get help message

### Have you tried a non-dockerized Jenkins and get the expected outcome?

Issue isn't related to Jenkins, just the docker image for jenkins.

### Output of `docker version`

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

### Other relevant information

I've tried this on 2 docker hosts, one windows and another a linux variant. Both have the same result.

After cloning this repo and building my own version this works fine so I suspect it was the most recent docker deploy to docker hub that somehow removed apt and possibly other utilities?

Example:

```
$ docker run -it --rm --user root jenkins/jenkins:lts apt-get update
/usr/local/bin/jenkins.sh: line 26: exec: apt-get: not found

$ git clone https://github.com/jenkinsci/docker.git
Cloning into 'docker'...
remote: Counting objects: 1830, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1830 (delta 1), reused 3 (delta 0), pack-reused 1824
Receiving objects: 100% (1830/1830), 341.82 KiB | 0 bytes/s, done.
Resolving deltas: 100% (961/961), done.

$ docker build -t jenkins/jenkins:personal-test .
Sending build context to Docker daemon  535.6kB
Step 1/34 : FROM openjdk:8-jdk
8-jdk: Pulling from library/openjdk
219d2e45b4af: Pull complete
a482fbcfe407: Pull complete
980edaaff53b: Pull complete
f44dc7c129fe: Pull complete
f34a55a78629: Pull complete
a0608417860f: Pull complete
74ffb0683f1a: Pull complete
11ab86bd63bc: Pull complete
a0e8d28e95f8: Pull complete
Digest: sha256:1f0c9158e5e3763a453d3a3449d765d3f20106aef89ec66581ec49d78c8b5eba
Status: Downloaded newer image for openjdk:8-jdk
 ---> 9f2e6cdfd7b4
Step 2/34 : RUN apt-get update && apt-get install -y git curl && rm -rf /var/lib/apt/lists/*
 ---> Running in 4ec55f7558ef
Get:1 http://security.debian.org stretch/updates InRelease [62.9 kB]
Ign:2 http://deb.debian.org/debian stretch InRelease
Get:3 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://security.debian.org stretch/updates/main amd64 Packages [200 kB]
Get:5 http://deb.debian.org/debian stretch Release [118 kB]
Get:6 http://deb.debian.org/debian stretch-updates/main amd64 Packages [5553 B]
Get:7 http://deb.debian.org/debian stretch Release.gpg [2373 B]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [9497 kB]
Fetched 9977 kB in 2s (4158 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.52.1-5).
git is already the newest version (1:2.11.0-3+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 ---> e5764fefcadf
Removing intermediate container 4ec55f7558ef
Step 3/34 : ARG user=jenkins
 ---> Running in 236973d9d276
 ---> 37c7c8a4deda
Removing intermediate container 236973d9d276
Step 4/34 : ARG group=jenkins
 ---> Running in edef8673ec1b
 ---> e7de613a1f77
Removing intermediate container edef8673ec1b
Step 5/34 : ARG uid=1000
 ---> Running in 2987b638fe74
 ---> de589fad7662
Removing intermediate container 2987b638fe74
Step 6/34 : ARG gid=1000
 ---> Running in dfbb5fff2eb9
 ---> 322e6f3161d0
Removing intermediate container dfbb5fff2eb9
Step 7/34 : ARG http_port=8080
 ---> Running in 8e51aaa8e001
 ---> c955124e66cd
Removing intermediate container 8e51aaa8e001
Step 8/34 : ARG agent_port=50000
 ---> Running in f416994ea3a7
 ---> 001ecfbf7cf5
Removing intermediate container f416994ea3a7
Step 9/34 : ENV JENKINS_HOME /var/jenkins_home
 ---> Running in 34274bcd3c3b
 ---> b5a4942f4828
Removing intermediate container 34274bcd3c3b
Step 10/34 : ENV JENKINS_SLAVE_AGENT_PORT ${agent_port}
 ---> Running in 0b8d8cebf3fa
 ---> 81f60add019e
Removing intermediate container 0b8d8cebf3fa
Step 11/34 : RUN groupadd -g ${gid} ${group}     && useradd -d "$JENKINS_HOME" -u ${uid} -g ${gid} -m -s /bin/bash ${user}
 ---> Running in 9de73c218036
 ---> 9a2705eb9a51
Removing intermediate container 9de73c218036
Step 12/34 : VOLUME /var/jenkins_home
 ---> Running in 9617fa6f400d
 ---> f5c2ffb85429
Removing intermediate container 9617fa6f400d
Step 13/34 : RUN mkdir -p /usr/share/jenkins/ref/init.groovy.d
 ---> Running in cd01a7bed1b5
 ---> 68afe2523db2
Removing intermediate container cd01a7bed1b5
Step 14/34 : ENV TINI_VERSION 0.14.0
 ---> Running in b50f9a5d6b20
 ---> 95a5431d9cff
Removing intermediate container b50f9a5d6b20
Step 15/34 : ENV TINI_SHA 6c41ec7d33e857d4779f14d9c74924cab0c7973485d2972419a3b7c7620ff5fd
 ---> Running in 7eee9ce65c81
 ---> 9ffeb0f74eda
Removing intermediate container 7eee9ce65c81
Step 16/34 : RUN curl -fsSL https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-static-amd64 -o /bin/tini && chmod +x /bin/tini   && echo "$TINI_SHA  /bin/tini" | sha256sum -c -
 ---> Running in 19290b9d223f
/bin/tini: OK
 ---> f8774f06b5c9
Removing intermediate container 19290b9d223f
Step 17/34 : COPY init.groovy /usr/share/jenkins/ref/init.groovy.d/tcp-slave-agent-port.groovy
 ---> 80e5232cfb47
Removing intermediate container f5601fc869b2
Step 18/34 : ARG JENKINS_VERSION
 ---> Running in 2492f2da2e15
 ---> 2c7372032349
Removing intermediate container 2492f2da2e15
Step 19/34 : ENV JENKINS_VERSION ${JENKINS_VERSION:-2.60.3}
 ---> Running in 4ecc18606e8b
 ---> 7b1114fc3823
Removing intermediate container 4ecc18606e8b
Step 20/34 : ARG JENKINS_SHA=2d71b8f87c8417f9303a73d52901a59678ee6c0eefcf7325efed6035ff39372a
 ---> Running in d891e648adea
 ---> 37f6e139e98e
Removing intermediate container d891e648adea
Step 21/34 : ARG JENKINS_URL=https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/${JENKINS_VERSION}/jenkins-war-${JENKINS_VERSION}.war
 ---> Running in f803ca3d7bde
 ---> 838838cced36
Removing intermediate container f803ca3d7bde
Step 22/34 : RUN curl -fsSL ${JENKINS_URL} -o /usr/share/jenkins/jenkins.war   && echo "${JENKINS_SHA}  /usr/share/jenkins/jenkins.war" | sha256sum -c -
 ---> Running in 6913ee8045c0
/usr/share/jenkins/jenkins.war: OK
 ---> 3fc95ba6216a
Removing intermediate container 6913ee8045c0
Step 23/34 : ENV JENKINS_UC https://updates.jenkins.io
 ---> Running in 0e5cc0fc2a13
 ---> cf8f55f01685
Removing intermediate container 0e5cc0fc2a13
Step 24/34 : ENV JENKINS_UC_EXPERIMENTAL https://updates.jenkins.io/experimental
 ---> Running in bfea22de1c09
 ---> ac17c8f3a220
Removing intermediate container bfea22de1c09
Step 25/34 : RUN chown -R ${user} "$JENKINS_HOME" /usr/share/jenkins/ref
 ---> Running in de4fe7efbaaa
 ---> 8237053f430a
Removing intermediate container de4fe7efbaaa
Step 26/34 : EXPOSE ${http_port}
 ---> Running in d69eb4a65ea4
 ---> 2ce0c0c2be8f
Removing intermediate container d69eb4a65ea4
Step 27/34 : EXPOSE ${agent_port}
 ---> Running in 831d7cb61746
 ---> f1e3ab2eff5e
Removing intermediate container 831d7cb61746
Step 28/34 : ENV COPY_REFERENCE_FILE_LOG $JENKINS_HOME/copy_reference_file.log
 ---> Running in fc5a73a2ede2
 ---> 5d0c46b98a89
Removing intermediate container fc5a73a2ede2
Step 29/34 : USER ${user}
 ---> Running in 7f2c0e775fa1
 ---> 0296c5a8de13
Removing intermediate container 7f2c0e775fa1
Step 30/34 : COPY jenkins-support /usr/local/bin/jenkins-support
 ---> 677d8010ebde
Removing intermediate container b3c5653d5f7a
Step 31/34 : COPY jenkins.sh /usr/local/bin/jenkins.sh
 ---> b5d6c6dd14be
Removing intermediate container caf8e7563645
Step 32/34 : ENTRYPOINT /bin/tini -- /usr/local/bin/jenkins.sh
 ---> Running in 0011ab2ec244
 ---> bf8c20e7fd1c
Removing intermediate container 0011ab2ec244
Step 33/34 : COPY plugins.sh /usr/local/bin/plugins.sh
 ---> 2807ec70b8c8
Removing intermediate container 8f9457b2c363
Step 34/34 : COPY install-plugins.sh /usr/local/bin/install-plugins.sh
 ---> c33eb51e3991
Removing intermediate container 4dad892957d8
Successfully built c33eb51e3991
Successfully tagged jenkins/jenkins:personal-test
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

$ docker run -it --rm jenkins/jenkins:personal-test apt-get
apt 1.4.7 (amd64)
Usage: apt-get [options] command
       apt-get [options] install|remove pkg1 [pkg2 ...]
       apt-get [options] source pkg1 [pkg2 ...]

apt-get is a command line interface for retrieval of packages
and information about them from authenticated sources and
for installation, upgrade and removal of packages together
with their dependencies.

Most used commands:
  update - Retrieve new lists of packages
  upgrade - Perform an upgrade
  install - Install new packages (pkg is libc6 not libc6.deb)
  remove - Remove packages
  purge - Remove packages and config files
  autoremove - Remove automatically all unused packages
  dist-upgrade - Distribution upgrade, see apt-get(8)
  dselect-upgrade - Follow dselect selections
  build-dep - Configure build-dependencies for source packages
  clean - Erase downloaded archive files
  autoclean - Erase old downloaded archive files
  check - Verify that there are no broken dependencies
  source - Download source archives
  download - Download the binary package into the current directory
  changelog - Download and display the changelog for the given package

See apt-get(8) for more information about the available commands.
Configuration options and syntax is detailed in apt.conf(5).
Information about how to configure sources can be found in sources.list(5).
Package and version choices can be expressed via apt_preferences(5).
Security details are available in apt-secure(8).
                                        This APT has Super Cow Powers.
```

### PR DESCRIPTION
**Pull request by carlossg**
Ensure that we don't publish when we receive unexpected http codes

This still doesn't yet explain why alpine and debian are overwriting each other

### CODE REVIEW

File: publish.sh [hunk 1]
```diff
@@ -44,7 +57,7 @@ get-manifest() {
     if [ "$debug" = true ]; then
         opts="-v"
     fi
-    curl $opts -q -fsSL -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -H "Authorization: Bearer $TOKEN" "https://index.docker.io/v2/jenkinsci/jenkins/manifests/$tag"
+    curl $opts -q -fsSL -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -H "Authorization: Bearer $TOKEN" "https://index.docker.io/v2/jenkins/jenkins/manifests/$tag"
```
Comment (oleg-nenashev) [inline publish.sh]: Maybe it explains it... 
It worth fixing the call destination anyway.

File: publish.sh [hunk 2]
```diff
@@ -84,8 +97,9 @@ publish() {
                  --build-arg "JENKINS_SHA=$sha" \
                  --tag "jenkins/jenkins:${tag}" \
                  --tag "jenkinsci/jenkins:${tag}" \
-                 "${build_opts[@]}" .
+                 "${build_opts[@]+"${build_opts[@]}"}" .
```
Comment (jjlin) [inline publish.sh]: What's the purpose of this?

Comment (carlossg) [reply publish.sh]: avoiding 

```
$ ./publish.sh -n
Dry run, will not publish images
Publishing version: 2.60.2
./publish.sh: line 82: build_opts[@]: unbound variable
```
